// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhTLRxGGvwgiSh85zg2K2uYYy_CeB0yjU',
    appId: '1:195997993798:web:28daa0604906571cb33347',
    messagingSenderId: '195997993798',
    projectId: 'sky-peace',
    authDomain: 'sky-peace.firebaseapp.com',
    storageBucket: 'sky-peace.appspot.com',
    measurementId: 'G-43EF2N72RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTTg7N6N9Lnhx5IRInTQMNCUf6bl1Rn0',
    appId: '1:195997993798:android:4476d2a51139b447b33347',
    messagingSenderId: '195997993798',
    projectId: 'sky-peace',
    storageBucket: 'sky-peace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8-JwfI3B1AXpU_W6w258QdI8yu-u_s8',
    appId: '1:195997993798:ios:11ddc5e0952cfd0fb33347',
    messagingSenderId: '195997993798',
    projectId: 'sky-peace',
    storageBucket: 'sky-peace.appspot.com',
    iosBundleId: 'com.example.skyPeace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8-JwfI3B1AXpU_W6w258QdI8yu-u_s8',
    appId: '1:195997993798:ios:11ddc5e0952cfd0fb33347',
    messagingSenderId: '195997993798',
    projectId: 'sky-peace',
    storageBucket: 'sky-peace.appspot.com',
    iosBundleId: 'com.example.skyPeace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhTLRxGGvwgiSh85zg2K2uYYy_CeB0yjU',
    appId: '1:195997993798:web:495360ff831a7c4bb33347',
    messagingSenderId: '195997993798',
    projectId: 'sky-peace',
    authDomain: 'sky-peace.firebaseapp.com',
    storageBucket: 'sky-peace.appspot.com',
    measurementId: 'G-4VVGDC3681',
  );

}